INSERT INTO Governments (Name,Image) VALUES ( 'Cairo','cairo.jpg');
INSERT INTO Governments (Name,Image) VALUES ( 'Giza','giza.jpg');
INSERT INTO Governments (Name,Image) VALUES ( 'Alexandria','alexandria.png');
INSERT INTO Governments (Name,Image) VALUES ( 'Dakahlia','dakahlia.jpg');
INSERT INTO Governments (Name,Image) VALUES ( 'Red Sea','redsea.jpg');
INSERT INTO Governments (Name,Image) VALUES ( 'Beheira','beheira.jpg');
INSERT INTO Governments (Name,Image) VALUES ( 'Fayoum','fayoum.jpg');
INSERT INTO Governments (Name,Image) VALUES ( 'Gharbia','gharbia.jpg');
INSERT INTO Governments (Name,Image) VALUES ( 'Ismailia','ismailia.jpg');
INSERT INTO Governments (Name,Image) VALUES ( 'Menofia','menofia.jpg');
INSERT INTO Governments (Name,Image) VALUES ( 'Minya','minia.jpg');
INSERT INTO Governments (Name,Image) VALUES ( 'Qaliubiya','qalyubia.jpg');
INSERT INTO Governments (Name,Image) VALUES ( 'Suez','suez.jpg');
INSERT INTO Governments (Name,Image) VALUES ( 'Aswan','aswan.jpg');
INSERT INTO Governments (Name,Image) VALUES ('Assiut','assiut.jpg');
INSERT INTO Governments (Name,Image) VALUES ('Beni Suef','benisuef.jpg');
INSERT INTO Governments (Name,Image) VALUES ('Port Said','portsaid.jpg');
INSERT INTO Governments (Name,Image) VALUES ('Damietta','damietta.jpg');
INSERT INTO Governments (Name,Image) VALUES ('Sharkia','sharkia.jpg');
INSERT INTO Governments (Name,Image) VALUES ('South Sinai','southsinai.jpg');
INSERT INTO Governments (Name,Image) VALUES ('Kafr El Sheikh','kafrelsheikh.jpg');
INSERT INTO Governments (Name,Image) VALUES ('Matrouh','matrouh.png');
INSERT INTO Governments (Name,Image) VALUES ('Luxor','luxor.jpg');
INSERT INTO Governments (Name,Image) VALUES ('Qena','qena.jpg');
INSERT INTO Governments (Name,Image) VALUES ('North Sinai','northsinai.png');
INSERT INTO Governments (Name,Image) VALUES ('Sohag','sohag.jpg');
